### PR TITLE
feat(docker): provide docker integration

### PR DESCRIPTION
**Pull request by TheDonDope**
Provide docker integration to being able to run within a container.

### CODE REVIEW

**Comment by mszep** [comment]
Whoa, this is awesome, thank you!

Out of curiosity though (and not knowing much about docker), what's the use case for running inside docker? Is it just to not have to install packages to the base system?

**Comment by TheDonDope** [comment]
Hey @mszep!

You are correct. My use-case was that i have multiple computers with different operating systems.  
A `apt-get install pandoc contex` may work easy enough on debian derivates, but what about windows for example?

So, with this PR, all you need is to have Docker installed on your machine, and no further prerequisites :)
I will update the PR with some minor changes, before i'd suggest it to be merged.

There is one pitfall however. My docker base image is ubuntu, which is a little heavyweight, especially the `apt-get update` and installing the dependencies takes a few minutes. However this is still a boatload faster than trying to install pandoc/context on windows :)

**Comment by TheDonDope** [comment]
Alright, i'm done!

**Comment by mszep** [comment]
Many thanks, will merge!

Incidentally, if you have any other suggestions for updates or enhancements, let me know!

**Pull request merged**
