### PR TITLE
replaced deprecated -S with -smart

### PR DESCRIPTION
**Pull request by billywade**
-S breaks some of the conversion. Fixed with changing to -smart.

### CODE REVIEW

**Comment by mszep** [comment]
Thanks for pointing this out!

What does the -smart option do again? Is it exclusive to docx and rtf output? If so, we'll need to figure out a workaround due to the new architecture of the Makefile.

**Comment by billywade** [comment]
I don't know much about it. I just know that the script failed with that as the error, but fixing it made everything come out right. It complained that a couple of other options were headed that way, and I'll look into updating those too before they break entirely.

**Comment by nitrocode** [comment]
So the version in Ubuntu Xenial is 1.16.0.2 and the latest [Pandoc is 2.1.2](https://github.com/jgm/pandoc/releases/tag/2.1.2) and the difference is the older version uses `--smart` whereas the new version uses `-smart`. In PR #37, I detected the pandoc version and applied the correct switch.

**Comment by billywade** [comment]
Great! I'm using an Arch variant, which explains the discrepancy.

**Comment by mszep** [comment]
Merged #37

**Pull request closed without merging**
